#!/bin/sh
DOTFILES=~/.dotfiles
CONFIG_STOW=$HOME
STOW_FILES=( "tmux" "tmux-sessionizer" "personal" "nvim" "sway" "rofi")
# Delete old config files before stowing
for dir in "${STOW_FILES[@]}"
do
	rm -rf $XDG_CONFIG_HOME/"$dir"
done

rm -f $HOME/.zshrc $HOME/.zsh_profile $HOME/.gitconfig
# Stow config files
stow -d "$DOTFILES" -t "$HOME" \
	pconfig \
	zsh \
	nvim \
	git \
	sway \
	rofi
