#!/bin/sh

yes | sudo dnf install tmux fzf


git clone https://github.com/ThePrimeagen/tmux-sessionizer.git ~/.local/bin/tmux-sessionizer
mv ~/.local/bin/tmux-sessionizer/tmux-sessionizer ~/.local/bin/
rm -rf ~/.local/bin/tmux-sessionizer
