#!/bin/sh

alias configsymls="symlinks -rv ~/"
alias vim="nvim"
alias pyenvact="source ./.venv/bin/activate"
alias exportcc="cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=1"
alias cmake_debug="cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=1"
alias cmake_release="cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=1"
alias cmake_reldeb="cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_EXPORT_COMPILE_COMMANDS=1"
