#!/bin/sh


bindkey -s ^f "tmux-sessionizer\n"
bindkey -s '\eq' "tmux-sessionizer 0\n"
bindkey -s '\ew' "tmux-sessionizer 1\n"
bindkey -s '\ee' "tmux-sessionizer 2\n"
bindkey -s '\er' "tmux-sessionizer 3\n"
